model_path: "/root/catkin_ws/src/self_supervised_segmentation/scripts/models/cocostuff27_vit_base_5.ckpt"
output_path: "/root/catkin_ws/src/self_supervised_segmentation/scripts/models/stego_cocostuff27_vit_base_5_cluster_linear_fine_tuning.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~